### ISSUE TITLE
Onslaught  v10.0.8

### ISSUE THREAD

**Issue by jimmywalles** [kaminaris/MaxDps-Warrior#22]
Hi,

Before this update the addon worked kinda good.
But now it keeps telling me i need to put Onslaught in my bars but i dont have it even selected in my talents.
Any way  to fix this?

My suggestion would be: implement it in settings so you can select your talents and make a rotation based on your selection.

kind regards,
jimmywalles

**Comment by doadin** [comment]
The rotation itself should check for talents, I didnt fix this till this commit: https://github.com/kaminaris/MaxDps-Warrior/commit/dd26018d769708d5c27bebe33614913aa45d50cf but this should be fixed now, I checked the rotation with and without, and the rotation works fine. This fix is included in v10.0.6+ of this warrior module. Please make sure you are up-to-date.
