### ISSUE TITLE
Berserker stance not found on action bars

### ISSUE THREAD

**Issue by Jonesy0000** [kaminaris/MaxDps-Warrior#23]
Since the previous update 10.0.4 I have been getting an error saying that berserker stance is not on my action bars. I then placed it there to see if that would fix the issue however it is the only thing that is circled on my action bar. Hoping this is fixed with .5

**Comment by Jonesy0000** [comment]
The above issue is fixed with .5 however now execute is not being suggested as part of the rotation.

**Comment by doadin** [comment]
execute should be fixed in 11.0.7 now. l;et me know if you have any other issues, thanks!

**Comment by Jonesy0000** [comment]
Great to hear, Thank you

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Jonesy0000** [comment]
This is still an issue
